name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-supabase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure Supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run: supabase start
      - name: Run tests
        run: supabase test db

  test-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: android

    steps:
    - uses: actions/checkout@v4
    - name: Configure Supabase
      uses: supabase/setup-cli@v1
      with:
        version: latest
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew buildDebug -PSUPABASE_URL_DEBUG="\"http://localhost:54321\""

    - name: Start Supabase
      run: supabase start
    - name: Test with Gradle
      run: ./gradlew testDebug -PSUPABASE_URL_DEBUG="\"http://localhost:54321\""